#!/bin/bash

set -euo pipefail

rm -rf slate/build
mkdir -p slate/build

shed/bootstrap

cd slate/build

../../configure CFLAGS=-I$HOME/local/include LDFLAGS=-L$HOME/local/lib --prefix=$HOME/local --enable-maintainer-mode --enable-rcl

make

