#!/bin/bash

set -euo pipefail

version=$(cat VERSION)
place="slate/rel-$version"

rm -rf $place
mkdir -p $place

cd $place

../../configure CFLAGS=-I$HOME/local/include LDFLAGS=-L$HOME/local/lib --prefix=$HOME/local

make install
CFLAGS=-I$HOME/local/include LDFLAGS=-L$HOME/local/lib make distcheck


