#!/bin/bash

set -euo pipefail

rm -rf build/copy
mkdir -p build/copy

shed/bootstrap

cd build/copy

../../configure CFLAGS=-I$HOME/local/include LDFLAGS=-L$HOME/local/lib --prefix=$HOME/local --enable-maintainer-mode

make

