#!/bin/bash

set -euo pipefail

version=$(cat VERSION)
place="build/rel-$version"

rm -rf $place
mkdir -p $place

# shed/setversion
# shed/bootstrap

cd $place

../../configure CFLAGS=-I$HOME/local/include LDFLAGS=-L$HOME/local/lib --prefix=$HOME/local

make
make dist


